### ISSUE TITLE
Seeding issue to setup a new marketplace

### ISSUE THREAD

**Issue by naveed-ahmad-biz** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#61]
Hi Team

I have it running on my local with an existing marketplace. There are some issues when I am trying to run the seed command around dependencies. Please see output both from the npm install and npm run seed commands:

`npm install`

---------------------------------------------
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: ordercloud-javascript-sdk@4.11.1
npm WARN Found: axios@0.21.4
npm WARN node_modules/@ordercloud/seeding/node_modules/axios
npm WARN   axios@"^0.21.1" from @ordercloud/seeding@1.0.31
npm WARN   node_modules/@ordercloud/seeding
npm WARN     dev @ordercloud/seeding@"^1.0.31" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer axios@"^0.19.2" from ordercloud-javascript-sdk@4.11.1
npm WARN node_modules/@ordercloud/seeding/node_modules/ordercloud-javascript-sdk
npm WARN   ordercloud-javascript-sdk@"^4.8.8" from @ordercloud/seeding@1.0.31
npm WARN   node_modules/@ordercloud/seeding
npm WARN
npm WARN Conflicting peer dependency: axios@0.19.2
npm WARN node_modules/axios
npm WARN   peer axios@"^0.19.2" from ordercloud-javascript-sdk@4.11.1
npm WARN   node_modules/@ordercloud/seeding/node_modules/ordercloud-javascript-sdk
npm WARN     ordercloud-javascript-sdk@"^4.8.8" from @ordercloud/seeding@1.0.31
npm WARN     node_modules/@ordercloud/seeding

added 1 package, and audited 1027 packages in 1s

146 packages are looking for funding
  run npm fund for details

found 0 vulnerabilities

-----------------------------
`npm run seed -- -u=xxxx -p=xxxx -n=marketplace`

------------------------------------------------------------------
ocsellerapp@0.1.0 seed
seeding seed playshop-marketplace.yml "-u=xxxx" "-p=xxxx" "-n=oc-commerce-demo"

SUCCESS - Found file "playshop-marketplace.yml"
Starting [----------------------------------------] 0% | 0/1(node:10900) ExperimentalWarning: The Fetch API is an expere
(Use node --trace-warnings ... to show where the warning was created)
SUCCESS - Data validated and ready for seeding.
@ordercloud/seeding seed [data]

Create a new sandbox marketplace and seed data.

Positionals:
  data, d  Local file name or HTTP(S) link
                                       [string] [default: "ordercloud-seed.yml"]

Options:
  --version       Show version number                                  [boolean]
  --help          Show help                                            [boolean]
  --username, -u  Portal username                                       [string]
  --password, -p  Portal password                                       [string]
  --id, -i        Marketplace ID                                        [string]
  --name, -n      Marketplace Name                                      [string]
  --regionId, -r  Region for the marketplace. See the API docs for more
                  information                                           [string]

TypeError: Cannot read properties of undefined (reading 'data')
    at C:\Projects\oc-commerce-demo\node_modules\@ordercloud\seeding\dist\cli.js:2433:201
    at step (C:\Projects\oc-commerce-demo\node_modules\@ordercloud\seeding\dist\cli.js:82:23)
    at Object.throw (C:\Projects\oc-commerce-demo\node_modules\@ordercloud\seeding\dist\cli.js:63:53)
    at rejected (C:\Projects\oc-commerce-demo\node_modules\@ordercloud\seeding\dist\cli.js:54:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by robertsoniv** [comment]
Hi @naveed-ahmad-biz! I will get somebody to help you shortly. We're still working out the kinks on getting better notifications when new issues are posted so sorry we didn't see this right away.

**Comment by robertsoniv** [comment]
https://github.com/ordercloud-api/portal-javascript-sdk/issues/1

**Comment by robertsoniv** [comment]
@naveed-ahmad-biz this has been fixed on the `main` branch. You'll have to re-run the `npm install` step to get the updated dependency.

**Comment by naveed-ahmad-biz** [comment]
@robertsoniv Thanks for the update. I tried it and it worked!
